export const allPortfolio = [
  {
    id: 1,
    category: "personal",
    title: "Video Game Web Site",
    img: "assets/iphone.png",
    description: "HTML & CSS",
    formation: "Autodidacte",
  },
  {
    id: 2,
    category: "school",
    title: "Chablais Property",
    img: "assets/property.png",
    description: "Ruby On Rails",
    formation: "Autodidacte",
  },
  {
    id: 3,
    category: "school",
    title: "Pro Tips",
    img: "assets/pro_tips.png",
    description: "Ruby On Rails",
    formation: "School Captstone Project",
  },
  {
    id: 4,
    category: "personal",
    title: "Covid Web Site",
    img: "assets/covid_website.png",
    description: "HTML & CSS",
    formation: "School Captstone Project",
  },
  {
    id: 5,
    category: "school",
    title: "Project 2 Javascript",
    img: "assets/javascript_project.png",
    description: "Javascript",
    formation: "School Captstone Project",
  },
  {
    id: 5,
    category: "school",
    title: "Project 3 Ruby on Rails",
    img: "assets/pinterest.png",
    description: "Ruby On rails",
    formation: "School Captstone Project",
  },
];
